server:
  port: 8090

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/springbootfinal
    username: postgres
    password: 29092003@Guru
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
