spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: postgres
    password: Anushka@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Use 'validate', 'update', 'create', or 'create-drop' as needed
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8082  # You can change this if needed

logging:
  level:
    org.springframework: INFO
    com.yourcompany.paymentservice: DEBUG  # Adjust package name as needed
