spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/springbootfinal
    username: postgres
    password: Anushka@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
